#!/usr/bin/env python3
"""
Raw Ingestion Layer for OCSF data

This module provides a class-based interface for ingesting OCSF JSON files into PostgreSQL.
Can be used as a library (imported by other scripts) or as a standalone CLI tool.

Usage as CLI (ingestion only):
    python ingest_raw_ocsf_findings.py --input-file <file.ocsf.json>
    python ingest_raw_ocsf_findings.py --input-file <file.ocsf.json> --schema custom_schema

Usage as Library (ingestion only - caller must validate separately):
    from ingest_raw_ocsf_findings import OCSFIngestor

    ingestor = OCSFIngestor(schema="boann_landing")  # schema is optional, defaults to "boann_landing"
    success = ingestor.ingest_file("/path/to/file.ocsf.json")

Data Model ({schema}.raw_ocsf_findings table):
- Table schema is managed by dbt (see raw_ocsf_findings.sql model)
- Each row corresponds to a single OCSF finding event
- JSONB column (raw_ocsf_json) stores the individual finding's JSON payload
- finding_uid acts as primary key for UPSERT operations
- loaded_at timestamp is generated by the database
- Schema defaults to "boann_landing" but is configurable
"""

import json
import logging
import os
import sys

from dotenv import load_dotenv
from sqlalchemy import TIMESTAMP, Column, MetaData, String, Table, create_engine, text
from sqlalchemy.dialects.postgresql import JSONB, insert

# Add parent directory to path for imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Import base CLI
from base_cli import BaseToolCLI


class OCSFIngestor:
    """
    OCSF File Ingestor - Ingests OCSF files into PostgreSQL.

    This class provides methods to ingest OCSF files into the
    raw_ocsf_findings table (schema is configurable, defaults to boann_landing).

    IMPORTANT: This class does NOT validate. Caller must ensure files are valid
    before calling ingest_file().
    """

    def __init__(self, database_url: str = None, schema: str = "boann_landing"):
        """
        Initialize the OCSF Ingestor.

        Args:
            database_url: Database connection URL (if None, uses DATABASE_URL env var)
            schema: Database schema name (default: boann_landing)
        """

        # Load database URL
        load_dotenv()
        self.database_url = database_url or os.getenv("DATABASE_URL")
        if not self.database_url:
            raise OSError("DATABASE_URL not set in environment or .env file")

        self.schema = schema

        # Create database engine and table definition
        self.db_engine = create_engine(self.database_url)
        self._setup_table_definition()

        self.logger = logging.getLogger(__name__)

    def _setup_table_definition(self):
        """Setup the SQLAlchemy table definition for raw_ocsf_findings."""
        metadata = MetaData(schema=self.schema)
        self.raw_ocsf_findings_table = Table(
            "raw_ocsf_findings",
            metadata,
            Column("finding_uid", String, primary_key=True),
            Column("raw_ocsf_json", JSONB, nullable=False),
            Column("loaded_at", TIMESTAMP(timezone=True), server_default=text("now()")),
            schema=self.schema,
        )

    def store_findings_to_db(self, ocsf_events_list: list, source_filename: str) -> int:
        """
        Loads a list of pre-validated OCSF finding events into the PostgreSQL landing table.

        Args:
            ocsf_events_list: List of OCSF event dictionaries
            source_filename: Name of the source file (for logging)

        Returns:
            Number of findings successfully stored

        Raises:
            Exception: If any finding fails to insert (fail-fast behavior)
        """
        total_loaded = 0

        self.logger.info("Storing %d validated events from %s.", len(ocsf_events_list), source_filename)

        for event in ocsf_events_list:
            finding_id = event.get("finding_info", {}).get("uid")

            try:
                stmt = (
                    insert(self.raw_ocsf_findings_table)
                    .values(
                        finding_uid=finding_id,
                        raw_ocsf_json=event,
                        loaded_at=text("CURRENT_TIMESTAMP"),
                    )
                    .on_conflict_do_update(
                        index_elements=["finding_uid"],
                        set_={
                            "raw_ocsf_json": event,
                            "loaded_at": text("CURRENT_TIMESTAMP"),
                        },
                    )
                )

                with self.db_engine.begin() as conn:
                    conn.execute(stmt)
                total_loaded += 1
                self.logger.debug("Upserted finding %s", finding_id)
            except Exception as e:
                self.logger.error("Failed to upsert finding %s: %s", finding_id, e, exc_info=True)
                raise

        return total_loaded

    def ingest_file(self, file_path: str) -> bool:
        """
        Main method to ingest an OCSF file into the database.

        IMPORTANT: This method does NOT validate the file. Caller must ensure
        the file is valid before calling this method.

        Args:
            file_path: Path to the OCSF file to ingest

        Returns:
            True if file was successfully ingested, False otherwise
        """
        file_name = os.path.basename(file_path)

        self.logger.info("--- OCSF Raw Ingestion Process Started ---")
        self.logger.info(f"Processing file: {file_path}")

        # Check file exists
        if not os.path.isfile(file_path):
            self.logger.error(f"Input file does not exist: {file_path}")
            return False

        if not file_path.endswith(".ocsf.json"):
            self.logger.error(f"Input file is not an OCSF JSON file: {file_path}")
            return False

        try:
            # Load and parse JSON
            with open(file_path, encoding="utf-8") as f:
                ocsf_data = json.load(f)

            # Store to database
            findings_count = self.store_findings_to_db(ocsf_data, file_name)

            if findings_count == 0:
                self.logger.info(f"No findings found in {file_name} (empty file).")
            else:
                self.logger.info(f"Successfully loaded {findings_count} findings from {file_name}.")

            self.logger.info("--- OCSF Raw Ingestion Process Complete (SUCCESS) ---")
            return True

        except json.JSONDecodeError as e:
            self.logger.error(f"Error parsing JSON from {file_name}: {e}. File is likely malformed.")
            return False
        except Exception as e:
            self.logger.error(f"Unexpected error during processing of {file_name}: {e}", exc_info=True)
            return False


class IngestorCLI(BaseToolCLI):
    """
    CLI interface for OCSF Ingestor.

    This CLI ingests OCSF files into the database.
    """

    def get_description(self) -> str:
        return "Raw Ingestion Layer for OCSF data. Ingests OCSF files into database."

    def get_epilog(self) -> str:
        return (
            "Returns exit code 0 on success, 1 on failure.\n\n"
            "Note: Use ocsf_monitor.py for batch processing with file management."
        )

    def add_arguments(self, parser):
        parser.add_argument("--input-file", type=str, required=True, help="Path to the OCSF input file to ingest")
        parser.add_argument(
            "--schema",
            type=str,
            default="boann_landing",
            help="Database schema name (default: boann_landing) where findings will be inserted",
        )

    def execute(self) -> int:
        """Execute ingestion."""
        try:
            self.logger.info("Ingesting OCSF file...")
            ingestor = OCSFIngestor(schema=self.args.schema)
            success = ingestor.ingest_file(self.args.input_file)

            return 0 if success else 1
        except Exception as e:
            self.logger.error(f"Failed to ingest file: {e}", exc_info=True)
            return 1


if __name__ == "__main__":
    sys.exit(IngestorCLI().run())
